//
// Created by stepavly on 27.02.2022.
//

#ifndef PARSER_GENERATOR_PARSER_RULE_UTILS_H_
#define PARSER_GENERATOR_PARSER_RULE_UTILS_H_

enum struct RULE_TYPE {
  TRANSITION,
  TRANSITION_REGEX,
  ASSIGN_RULE,
  ASSIGN_TEXT,
  ASSIGN_REGEX,
  TEXT,
  CALL
};

#endif //PARSER_GENERATOR_PARSER_RULE_UTILS_H_
